from checkmate import checkmate

def main():
    # Test Case 1: Rook ยิง King (Success)
    board1 = """\
R...
.K..
..P.
...."""
    
    # Test Case 2: King ปลอดภัย (Fail)
    board2 = """\
..
.K"""

    # Test Case 3: Bishop ยิง King (Success)
    board3 = """\
B...
.K..
....
...."""

    # Test Case 4: มีตัวบัง (Fail)
    board4 = """\
B...
.P..
..K.
...."""
     # Test Case 5: Bigger board
    board5 =  """
.........
.........
.........
.........
....B....
.........
.........
.........
K........"""


 # Test Case 6: Board not symetric ERROR
    board5 =  """
............
............
...........
...........
....B....
........
.........
.........
K........"""

    board6 = """
RB.K....
P.......
........
........
........
........
P......P
R.BQ...."""

    print(f"Board 1 (Expect Success): {checkmate(board1)}")
    print(f"Board 2 (Expect Fail): {checkmate(board2)}")
    print(f"Board 3 (Expect Success): {checkmate(board3)}")
    print(f"Board 4 (Expect Fail): {checkmate(board4)}")
    print(f"Board 5 (Expect Error): {checkmate(board5)}")
    print(f"Board 6 (Expect Success): {checkmate(board6)}")

if __name__ == "__main__":
    main()